FROM alpine:3.22

RUN apk add --no-cache iproute2 nftables usbutils

COPY scripts/network-init.sh /usr/local/bin/jurius-network-init
RUN chmod 0755 /usr/local/bin/jurius-network-init

ENTRYPOINT ["/usr/local/bin/jurius-network-init"]
